### ISSUE TITLE
What is the purpose of being able to submit issues here?

### ISSUE THREAD

**Issue by AmarThakkar** [ibm-cloud-docs/cloud-pak-data#1]
Hello,

What is the purpose or reasoning behind being able to submit issues here? Is it for product issues or product doc issues? The reason to ask is I see the repo hierarchy as being:

ibm-cloud-docs/cloud-pak-data

Thank you.

**Comment by juliabamford** [comment]
@AmarThakkar This is specific to requesting changes to the IBM Cloud docs for IBM Cloud Pak for Data.

**Comment by patsmith-public** [comment]
Julia addressed this issue
